### PR TITLE
Fixed undefined/null check

### LINKED ISSUE #329: Media library does not show files in static resource

### PR DESCRIPTION
**Pull request by lauriLukkarinen**
Resolves #329

### CODE REVIEW

File: src/components/content-editor/resource-editor.tsx [hunk 1]
```diff
@@ -141,13 +141,15 @@ class ResourceEditor extends React.Component<Props, State> {
   private renderResourceField = () => {
     const { classes, accessToken, resource } = this.props;
 
+    console.log("static resource - type: ", resource.type);
+
```
Comment (jarinykanen) [inline src/components/content-editor/resource-editor.tsx:145]: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARGH!
```suggestion
    console.log("static resource - type: ", resource.type);

```

**Review by jarinykanen — APPROVED** [review]
